\contentsline {lstlisting}{\numberline {1}\IeC {\textKappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } \IeC {\textepsilon }\IeC {\textkappa }\IeC {\textkappa }\IeC {\'\textiota }\IeC {\textnu }\IeC {\texteta }\IeC {\textsigma }\IeC {\texteta }\IeC {\textvarsigma }}{5}{}%
\contentsline {lstlisting}{\numberline {2}\IeC {\textKappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } goal\_found}{5}{}%
\contentsline {lstlisting}{\numberline {3}\IeC {\textTau }\IeC {\textupsilon }\IeC {\textpi }\IeC {\textiota }\IeC {\textkappa }\IeC {\'\textomicron }\IeC {\textvarsigma } \IeC {\textkappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } \IeC {\textkappa }\IeC {\'\textiota }\IeC {\textnu }\IeC {\texteta }\IeC {\textsigma }\IeC {\texteta }\IeC {\textvarsigma }}{6}{}%
\contentsline {lstlisting}{\numberline {4}\IeC {\textBeta }\IeC {\'\texteta }\IeC {\textmu }\IeC {\textalpha } 1}{7}{}%
\contentsline {lstlisting}{\numberline {5}\IeC {\textTau }\IeC {\textrho }\IeC {\textomicron }\IeC {\textpi }\IeC {\textomicron }\IeC {\textpi }\IeC {\textomicron }\IeC {\textiota }\IeC {\'\texteta }\IeC {\textmu }\IeC {\textepsilon }\IeC {\textnu }\IeC {\textomicron }\IeC {\textvarsigma } \IeC {\textgamma }\IeC {\textepsilon }\IeC {\textnu }\IeC {\textiota }\IeC {\textkappa }\IeC {\'\textomicron }\IeC {\textvarsigma } \IeC {\textkappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } \IeC {\textkappa }\IeC {\'\textiota }\IeC {\textnu }\IeC {\texteta }\IeC {\textsigma }\IeC {\texteta }\IeC {\textvarsigma }}{15}{}%
\contentsline {lstlisting}{\numberline {6}\IeC {\textKappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } prompt}{16}{}%
\contentsline {lstlisting}{\numberline {7}\IeC {\textTau }\IeC {\textupsilon }\IeC {\textpi }\IeC {\textiota }\IeC {\textkappa }\IeC {\'\textomicron }\IeC {\textvarsigma } \IeC {\textkappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } \IeC {\textepsilon }\IeC {\textpi }\IeC {\textiota }\IeC {\textsigma }\IeC {\texttau }\IeC {\textrho }\IeC {\textomicron }\IeC {\textphi }\IeC {\'\texteta }\IeC {\textvarsigma } \IeC {\textsigma }\IeC {\texttau }\IeC {\textomicron } s2}{17}{}%
\contentsline {lstlisting}{\numberline {8}\IeC {\textTau }\IeC {\textupsilon }\IeC {\textpi }\IeC {\textiota }\IeC {\textkappa }\IeC {\'\textomicron }\IeC {\textvarsigma } \IeC {\textkappa }\IeC {\textalpha }\IeC {\textnu }\IeC {\'\textomicron }\IeC {\textnu }\IeC {\textalpha }\IeC {\textvarsigma } \IeC {\textepsilon }\IeC {\'\textupsilon }\IeC {\textrho }\IeC {\textepsilon }\IeC {\textsigma }\IeC {\texteta }\IeC {\textvarsigma } \IeC {\textalpha }\IeC {\textupsilon }\IeC {\texttau }\IeC {\textomicron }\IeC {\textkappa }\IeC {\'\textiota }\IeC {\textnu }\IeC {\texteta }\IeC {\texttau }\IeC {\textomicron }\IeC {\textupsilon }}{18}{}%
\contentsline {lstlisting}{\numberline {9}\IeC {\textBeta }\IeC {\'\texteta }\IeC {\textmu }\IeC {\textalpha } 2}{19}{}%
